from src.exercises.palindrome import is_palindrome

def test_is_palindrome():

    test_cases = [
        ("", False),
        ("a", False),
        ("aa", True),
        ("aba", True),
        ("abba", True),
        ("abca", False),
        ("abcba", True),
        ("abcdcba", True),
        ("abcd", False),
        ("abcddcba", True),
        ("abcdd", False),
        ("tattarrattat", True),
        ("tattarrattatx", False),
        ("tattarrattaty", False),
        ("tattarrattatz", False),
        ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", True),
        ("aaaaaaaaaaaaaa", True),
        ("aaaaaaaaaaaaaab", False),
        ("aaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", False),
        ("aaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaa", False),
        ("dogeeseseegod", True),
        ("", False),
        ("a", False),
        ("aa", True),
        ("aaa", True),
        ("aba", True),
        ("abba", True),
        ("abca", False),
        ("abcba", True),
        ("abcdcba", True),
        ("abcd", False),
        ("abcddcba", True),
        ("abcdd", False),
        ("tattarrattat", True),
        ("tattarrattatx", False),
        ("tattarrattaty", False),
        ("tattarrattatz", False),
        ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", True),
        ("aaaaaaaaaaaaaa", True),
        ("aaaaaaaaaaaaaab", False),
        ("aaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", False),
        ("aaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaa", False),
        ("dogeeseseegod", True),
        ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", True),
        ("aaaaaaaaaaaaaa", True),
        ("aaaaaaaaaaaaaab", False),
        ("aaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", False),
        ("aaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaa", False),
        ("dogeeseseegod", True),
        ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", True),
        ("aaaaaaaaaaaaaa", True),
        ("aaaaaaaaaaaaaab", False),
        ("aaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", False),
        ("aaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaa", False),
        ("dogeeseseegod", True),
        ("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", True),
        ("aaaaaaaaaaaaaa", True),
        ("aaaaaaaaaaaaaab", False),
        ("aaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", False),
        ("aaaaaaaaaaaaaabaaaaaaaaaaaaaaaaaaaaaaa", False)
    ]

    for (test_input, expected_result) in test_cases:
        assert is_palindrome(test_input) == expected_result